### ISSUE TITLE
Meeting Memos

### ISSUE THREAD

**Issue by box-key** [SiameseLab/quesadiya#15]
- [x] **bug**: Add a function to remove an username in `triplet_dataset` when admin deletes the user. For example, when admin removes `col1`, it removes all `col1` in `username` field in `triplet_dataset` table in `project.db`. 
- [x] **bug**: `Add New` doesn't have a button to add new collaborator.

**Comment by WinThureinMyint** [comment]
bug: Add New doesn't have a button to add new collaborator.

I disabled the "Add New" button while Admin user tying to add new collaborator. When they done, it'll be enable the button.
