### ISSUE TITLE
Admin Page

### ISSUE THREAD

**Issue by box-key** [SiameseLab/quesadiya#20]
- [x] I think admin should be able to see what a discarded sample is in `Discarded` tab. For example, by clicking `Anchor Sample ID`, they can view sample (without `select` and `discarded` buttons).
- [x] I found that there is no way to remove collaborator in the current version bc it doesn't allow the empty username and password. I think we can only provide `add new` and `remove` option (probably replacing `Edit` button with `Remove` option).

**Comment by WinThureinMyint** [comment]
[] I found that there is no way to remove collaborator in the current version bc it doesn't allow the empty username and password. I think we can only provide add new and remove option (probably replacing Edit button with Remove option).

solved: 
It have been solve while solving the Meeting Memos #15 bug.
